In [1]:
import pandas as pd

In [2]:
info = {
    "Name":['Nikesh','Rahul','Apil'],
    "CGPA":[9.5,7.5,8.5]
}
df=pd.DataFrame(info)

In [3]:
df

     Name  CGPA
0  Nikesh   9.5
1   Rahul   7.5
2    Apil   8.5

# series

In [4]:
s=pd.Series([1,2,3,4,5])
print(s)
print(type(s))

# index
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
3

In [5]:
s = pd.Series([23,24,25,26],index=["Adam","Eve","Bob","Charlie"])
s
# These names are actually named index(labels)

Adam       23
Eve        24
Bob        25
Charlie    26
dtype: int64

In [6]:
print(s["Adam"]) 
print(s["Eve"])

23
24

In [7]:
print(s.index)

Index(['Adam', 'Eve', 'Bob', 'Charlie'], dtype='object')

In [8]:
# vectorized operations
s1 = pd.Series([11,12,34,45])
s2 = pd.Series([11,12,35,45])
print(s1 + s2)

s1[0]=100
print(s1[0])

changed_s1 = s1.drop(0)
print(s1)
print(changed_s1)

0    22
1    24
2    69
3    90
dtype: int64
100
0    100
1     12
2     34
3     45
dtype: int64
1    12
2    34
3    45
dtype: int64

# DataFrame

In [9]:
info = {
    "Name":['Adam',"Eve","Bob"],
    "Age":[23,24,25],
    "GPA":[9.5,8.5,7.2]
}
df=pd.DataFrame(info)
print(df)

   Name  Age  GPA
0  Adam   23  9.5
1   Eve   24  8.5
2   Bob   25  7.2

In [10]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [11]:
print(df.columns)

Index(['Name', 'Age', 'GPA'], dtype='object')

In [12]:
# lists of lists
df = pd.DataFrame([["Adam",23],["Nikesh",22],["Eve",23]],columns=["Name","Age"])

In [13]:
print(df)

     Name  Age
0    Adam   23
1  Nikesh   22
2     Eve   23

In [14]:
import numpy as np
np_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(np_arr,columns=["A","B","C"])

In [16]:
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9